### ISSUE TITLE
Discussion: Add an OSS License?

### ISSUE THREAD

**Issue by typhonrt** [LeaVerou/css.land#17]
Hi, 

Any chance that an OSS license can be posted for this repo? I'm working on an open source LCH based dynamic theming engine for a particular gaming platform ([FoundryVTT](https://foundryvtt.com/)). This also happens to be the non-trivial demo code for a new Svelte based runtime / UI component library I'm putting out. So I'll be making a separate set of Svelte components for working with LCH. I'd like to examine using the conversion code in this repo to support Rec2020, P3, etc. as well as provide a guide / inspiration for implementing the Svelte LCH color picker (IE similar slider display). 

It would be fantastic to have an exact license to add / reference for this repo. From the associated blog post and the backgrounds of those involved it appears this repo / code is meant to inform and help folks and bring awareness. 

It would also be great to get an idea of licensing aspects to the following referenced source files: 
```
https://drafts.csswg.org/css-color-4/multiply-matrices.js
https://drafts.csswg.org/css-color-4/conversions.js
https://drafts.csswg.org/css-color-4/utilities.js
```

`multiply-matrices.js` has a brief MIT attribution and there are statements say in `conversions.js` on where info was sourced. I know this is the sample code provided from [css-color-4 draft](https://drafts.csswg.org/css-color-4/#color-conversion-code), but it is not clearly marked there either.

**Comment by LeaVerou** [comment]
Added a license. Pinging @svgeesus for `conversions.js` and `utilities.js`.
