### ISSUE TITLE
[lch] Use color(display-p3) when available

### ISSUE THREAD

**Issue by focalstrategy** [LeaVerou/css.land#5]
I might be wrong but on Safari the colours here seem to be the srgb gamut, rather than the p3 or the rec2020 version.

Or maybe I’m wrong and am just not paying attention!

**Comment by LeaVerou** [comment]
Yup, it's top on my list of things to improve. I had missed that Safari not only finished implementing this, but did so in 2017!! How exciting. Thanks for creating a bug report, I'll track it here.

**Comment by LeaVerou** [comment]
Ping @svgeesus to add conversion math to his conversion library (or confirm that it's already there).

**Comment by focalstrategy** [comment]
> Yup, it's top on my list of things to improve. I had missed that Safari not only finished implementing this, but did so in 2017!! How exciting. Thanks for creating a bug report, I'll track it here.

Awesome - yeah, the p3 color exists on iOS and Macs, so for some UK retail web sites we work on that is >50%!
